progressonderwijs/ProgressOnderwijsUtils

src/ProgressOnderwijsUtils/MetaAttributes.cs
Useful for xml, webservices, json, etc
=> Added attribute to mark fields used by serialisation

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
Dit voorkomt waarschuwingen tijdens de build van PNet
=> Update reference to nuget package

src/ProgressOnderwijsUtils/MetaObject/MetaObjectBulkCopy.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
Just provide your own transaction using SqlConnection.EnlistTransaction
=> Don't specify UseInternalTransaction in BulkCopyToSqlServer

How-to-push-to-nuget.txt, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SingleSignOn/AuthnRequest.cs, src/ProgressOnderwijsUtils/SingleSignOn/SsoProcessor.cs, test/ProgressOnderwijsUtilsTests/CollectionBehavior.cs, test/ProgressOnderwijsUtilsTests/ProgressOnderwijsUtilsTests.csproj, tools/HtmlFragmentBenchmark/HtmlFragmentBenchmark.csproj, tools/MicroOrmBench/MicroOrmBench.csproj
Vaag verhaal over ForceAuthn hier: https://wiki.surfnet.nl/display/surfconextdev/Authentication+request%3A+bindings%2C+signing+and+options, maar het lijkt te werken bij Stenden.
=> Improvements SAML api

src/ProgressOnderwijsUtils/Data/CommandFactory.cs, src/ProgressOnderwijsUtils/ImageTools.cs, src/ProgressOnderwijsUtils/SingleSignOn/SsoProcessor.cs, src/ProgressOnderwijsUtils/WebSupport/SecureHttpOnlySessionCookieModule.cs, test/ProgressOnderwijsUtilsTests/TypeExtensionTest.cs
Stuff I came across while doing the nullability annotations.
None of this should change the code semantics.
=> Various cleanups to make resharper happy

src/ProgressOnderwijsUtils/Extensions/DictionaryExtensions.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
(We'll need to check this in PNet!)
=> DictionaryExtensions.Clone: Non-null api

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SingleSignOn/SsoAttributes.cs, src/ProgressOnderwijsUtils/SingleSignOn/SsoProcessor.cs
This is where SurfConext stores the LoA: https://wiki.surfnet.nl/display/surfconextdev/Using+Levels+of+Assurance+to+express+strength+of+authentication
=> Include AuthnContextClassRef in SsoAttributes

src/ProgressOnderwijsUtils.AspNetCore/ProgressOnderwijsUtils.AspNetCore.csproj, src/ProgressOnderwijsUtils.Drawing/ProgressOnderwijsUtils.Drawing.csproj, src/ProgressOnderwijsUtils.Web/ProgressOnderwijsUtils.Web.csproj, src/ProgressOnderwijsUtils/Data/CascadedDelete.cs, src/ProgressOnderwijsUtils/Data/CommandFactory.cs, src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs, src/ProgressOnderwijsUtils/MetaObject/MetaObjectBulkCopy.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Drawing.Tests/ProgressOnderwijsUtils.Drawing.Tests.csproj, test/ProgressOnderwijsUtils.Tests/Data/CascadedDeleteTest.cs, test/ProgressOnderwijsUtils.Tests/ProgressOnderwijsUtils.Tests.csproj, tools/ProgressOnderwijsUtilsBenchmarks/ProgressOnderwijsUtilsBenchmarks.csproj
- Support deleting from initial tables with multiple pk columns
- and support following FKs into tables that themselves have no PK
- support optionally returning the actually deleted rows in an output clause.
=> Improve Cascaded deletion

src/ProgressOnderwijsUtils/Data/CascadedDelete.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
May have been the cause of some of the flaky tests on pcjenkins2015.
=> Fix cascade delete concurrency risk

src/ProgressOnderwijsUtils/Utils.cs
Obsoleet, naar Progress verhuisd
=> Verwijder SLMaybeIncompleteDateConversion

src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs
(e.g. https://github.com/progressonderwijs/progress/pull/16219)
So that the exception does not read:
```
---- System.InvalidOperationException : Cannot unpack column ExterneToelating of type bit (C#:bool) into InschrijvingOpleidingRij.ExterneToelating of type bool
-------- System.Data.SqlTypes.SqlNullValueException : Data is Null. This method or property cannot be called on Null values.
at ProgressOnderwijsUtils.ParameterizedSqlObjectMapper.ReadMetaObjects[T](ParameterizedSql q, SqlCommandCreationContext qCommandCreationContext)
```
but 
```
---- System.InvalidOperationException : Cannot unpack NULL value from column ExterneToelating of type bit (C#:bool?) into InschrijvingOpleidingRij.ExterneToelating of type bool
-------- System.Data.SqlTypes.SqlNullValueException : Data is Null. This …
```
=> better error on unexpected nulls

src/ProgressOnderwijsUtils/Data/ParameterizedSqlExtensions.cs, src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- Remove AppendIf
- Support no-op execution of non-queries.
=> ParameterizedSql tweaks

src/ProgressOnderwijsUtils/Html/HtmlFragment.cs, src/ProgressOnderwijsUtils/Html/HtmlTagHelpers.cs, test/ProgressOnderwijsUtils.Tests/HtmlTests.cs
...and avoid perf cliffs or mega-many long-lived tiny objects.
=> Allow appending html fragments

src/ProgressOnderwijsUtils/Html/CustomHtmlElement.cs, src/ProgressOnderwijsUtils/Html/HtmlFragment.cs, src/ProgressOnderwijsUtils/Html/HtmlSpec.Generated.cs, src/ProgressOnderwijsUtils/Html/HtmlTagHelpers.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Tests/HtmlTests.cs, test/ProgressOnderwijsUtils.Tests/HtmlToStringApprovals.DocWithTrulyRawText.approved.txt, test/ProgressOnderwijsUtils.Tests/HtmlToStringApprovals.DocWithTrulyRawTextToCSharp.approved.txt, test/ProgressOnderwijsUtils.Tests/HtmlToStringApprovals.cs, tools/ParseHtml5Spec.linq
Recommend review by commit so the generated code noise is easier to ignore.
Also bump version so we can release this.
=> Implement HtmlFragment + operator

ProgressOnderwijsUtils.sln, src/NugetPackagesCommon.props, src/ProgressOnderwijsUtils.AspNetCore/ProgressOnderwijsUtils.AspNetCore.csproj, src/ProgressOnderwijsUtils.Drawing/ProgressOnderwijsUtils.Drawing.csproj, src/ProgressOnderwijsUtils.Web/ProgressOnderwijsUtils.Web.csproj, src/ProgressOnderwijsUtils/Data/OrderByColumns.cs, src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Drawing.Tests/ProgressOnderwijsUtils.Drawing.Tests.csproj, test/ProgressOnderwijsUtils.Tests/ProgressOnderwijsUtils.Tests.csproj
ref: https://github.com/dotnet/sourcelink/
=> Enable SourceLink support

src/ProgressOnderwijsUtils.AspNetCore/ProgressOnderwijsUtils.AspNetCore.csproj, src/ProgressOnderwijsUtils.Drawing/ProgressOnderwijsUtils.Drawing.csproj, src/ProgressOnderwijsUtils.Web/ProgressOnderwijsUtils.Web.csproj, src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
=> bump versions

src/ProgressOnderwijsUtils/Data/CascadedDelete.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Tests/Data/CascadedDeleteTest.cs
=> Added extra CascadeDelete.RecursivelyDelete overloads.

tools/ProgressOnderwijsUtilsBenchmarks/BenchmarkProgram.cs, tools/ProgressOnderwijsUtilsBenchmarks/HtmlFragmentBenchmark.cs, tools/ProgressOnderwijsUtilsBenchmarks/MicroOrmBench/BenchmarkUtil.cs, tools/ProgressOnderwijsUtilsBenchmarks/MicroOrmBench/ExampleObject.cs, tools/ProgressOnderwijsUtilsBenchmarks/MicroOrmBench/ParameterizedSqlExecutor.cs, tools/ProgressOnderwijsUtilsBenchmarks/MicroOrmBench/Program.cs
Solely as baseline for the next PR
=> Benchmark tweaks

src/ProgressOnderwijsUtils/Data/DbColumnDefinition.cs, src/ProgressOnderwijsUtils/Data/FieldMapping.cs, src/ProgressOnderwijsUtils/MetaObject/MetaProperty.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SchemaReflection/DbColumnMetaData.cs, test/ProgressOnderwijsUtils.Tests/MetaObjectBulkCopyTest.cs
Setting the actual index upon reading does the trick.
=> Use the column-index from the db itself, instead of assuming the order of the columns-array.

src/ProgressOnderwijsUtils/MetaObject/MetaObjectBulkCopy.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SchemaReflection/DbColumnMetaData.cs, test/ProgressOnderwijsUtils.Tests/MetaObjectBulkCopyFieldMappingTest.cs
=> Added MetaObjectBulkCopy overloads with extra column mapping parameter.

src/ProgressOnderwijsUtils.Drawing/ImageTools.cs, test/ProgressOnderwijsUtils.Tests/DeepEqualsTests.cs, test/ProgressOnderwijsUtils.Tests/FileInfoExtensionTest.cs, test/ProgressOnderwijsUtils.Tests/SqlErrorParserTest.cs, tools/ProgressOnderwijsUtilsBenchmarks/BenchmarkProgram.cs, tools/ProgressOnderwijsUtilsBenchmarks/HtmlFragmentBenchmark.cs
Reduce number of R# messages in utils.
=> Minor cleanups

src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs, test/ProgressOnderwijsUtils.Tests/MetaObjectPropertyLoaderTest.cs
in particular, don't assume all errors are due to column mapping.
=> Better error messages

test/ProgressOnderwijsUtils.Tests/MetaObjectBulkCopyTest.cs
=> Add test that requires the missing feature of auto-omitting identity columns

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
(die was ik vergeten in #186 )
=> Bump version

src/ProgressOnderwijsUtils/Collections/Maybe.cs, src/ProgressOnderwijsUtils/Collections/MaybeExtensions.cs, src/ProgressOnderwijsUtils/Collections/RootedTree.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Tests/MaybeTests.cs
=> Improve Maybe API

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Tests/ProgressOnderwijsUtils.Tests.csproj
All these dependencies now target netstandard
=> No longer suppress NU1701

src/ProgressOnderwijsUtils/ProcessRunner.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Drawing.Tests/ProgressOnderwijsUtils.Drawing.Tests.csproj, test/ProgressOnderwijsUtils.Tests/ProcessRunnerTest.cs, test/ProgressOnderwijsUtils.Tests/ProgressOnderwijsUtils.Tests.csproj, tools/ProgressOnderwijsUtilsBenchmarks/ArrayBuilderBenchmark.cs, tools/ProgressOnderwijsUtilsBenchmarks/ProgressOnderwijsUtilsBenchmarks.csproj
=> Fix ProcessRunner on .net core

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SingleSignOn/SsoProcessor.cs, test/ProgressOnderwijsUtils.Tests/SsoProcessorTest.cs
The fix is in https://github.com/progressonderwijs/ProgressOnderwijsUtils/commit/cfb67ca33a476b3114b79199e99a8650b4efc247
=> Revamp SsoProcessor and fix signature validation

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SingleSignOn/SsoProcessor.cs
Heb ik nodig om onze Google-organisatie als IDP te gebruiken (om de verkiezingen beter te kunnen testen).
=> Make domain in SsoAttributes optional

src/NugetPackagesCommon.props, src/ProgressOnderwijsUtils/Data/SqlCommandDebugStringifier.cs, src/ProgressOnderwijsUtils/Data/SqlTimeoutDetection.cs, src/ProgressOnderwijsUtils/Extensions/ExceptionExtensions.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/Utils.cs, test/ProgressOnderwijsUtils.Tests/UtilsTest.cs
...with some minor api tweaks (rename/as extension method).
=> Move Exception utils here

src/ProgressOnderwijsUtils/Html/HtmlFragment.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Tests/HtmlTests.cs
Ik ben er niet helemaal zeker van of dit the _way-to-go_ is, maar vooruit.
=> Pnet: voeg lege string check toe voor HtmlFragment.IsEmpty

appveyor.yml, src/NugetPackagesCommon.props, src/ProgressOnderwijsUtils/ApprovalTest.cs, src/ProgressOnderwijsUtils/Collections/CachedTreeBuilder.cs, src/ProgressOnderwijsUtils/Collections/MaybeExtensions.cs, src/ProgressOnderwijsUtils/Collections/Tree.cs, src/ProgressOnderwijsUtils/Data/BackingFieldDetector.cs, src/ProgressOnderwijsUtils/Data/CascadedDelete.cs, src/ProgressOnderwijsUtils/Data/CodeGenHelper.cs, src/ProgressOnderwijsUtils/Data/CommandFactory.cs, src/ProgressOnderwijsUtils/Data/FieldMapping.cs, src/ProgressOnderwijsUtils/Data/FromDbValueConverter.cs, src/ProgressOnderwijsUtils/Data/SiteBase.cs, src/ProgressOnderwijsUtils/Data/SqlCommandTracer.cs, src/ProgressOnderwijsUtils/Data/SqlParameterComponent.cs, src/ProgressOnderwijsUtils/Extensions/EnumerableExtensions.cs, src/ProgressOnderwijsUtils/Extensions/StringExtensions.cs, src/ProgressOnderwijsUtils/Extensions/StringUtils.cs, src/ProgressOnderwijsUtils/Extensions/ToStringInvariantExtension.cs, src/ProgressOnderwijsUtils/Extensions/TypeExtension.cs, src/ProgressOnderwijsUtils/Html/HtmlFragment.cs, src/ProgressOnderwijsUtils/Html/HtmlFragmentSanitizeExtension.cs, src/ProgressOnderwijsUtils/Html/HtmlToTextContent.cs, src/ProgressOnderwijsUtils/RsaStringSigner.cs, src/ProgressOnderwijsUtils/SingleSignOn/AuthnRequest.cs, src/ProgressOnderwijsUtils/SingleSignOn/SsoProcessor.cs, src/ProgressOnderwijsUtils/SourceLocation.cs, src/ProgressOnderwijsUtils/SqlErrorParser.cs, src/ProgressOnderwijsUtils/Utils.cs
Reverts progressonderwijs/ProgressOnderwijsUtils#289
Let's do this in a more orderly manner
=> Revert "Apply some nullable annotations"

test/ProgressOnderwijsUtils.Tests/PocoBulkCopyTest.cs
that slipped through the cracks with https://github.com/progressonderwijs/ProgressOnderwijsUtils/pull/295
=> Fix warnings

src/ProgressOnderwijsUtils/SqlErrorParser.cs
(cherry picked from commit da694d4ce1662ff2fcd79171d103cd52cc2f7b5f)
=> CanBeNull => ?

src/ProgressOnderwijsUtils/Extensions/UriExtensions.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Tests/UriExtensionsTest.cs
Zo I can use these extensions from my new Ods assembly without having to use the business-assembly.
=> Added Uri extensions for safely combining paths.

src/ProgressOnderwijsUtils/Html/HtmlHelpers.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Tests/HtmlTests.cs, test/ProgressOnderwijsUtils.Tests/HtmlToStringApprovals.cs
Allow setting multiple classes at once (move convenience code from progress to here)
=> Multi class extension

src/ProgressOnderwijsUtils/SchemaReflection/DatabaseDescription.cs
Not significantly faster on my machine.
=> Shorter, and simpler.

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SchemaReflection/DatabaseDescription.cs
Runtime loading from 58 ms to 57 ms.
=> Optimize code + runtime while loading the db-description.

tools/ProgressOnderwijsUtilsBenchmarks/BenchmarkProgram.cs, tools/ProgressOnderwijsUtilsBenchmarks/TreeBenchmark.cs
=> Add a really simple tree benchmark

src/ProgressOnderwijsUtils.AspNetCore/ProgressOnderwijsUtils.AspNetCore.csproj
(cherry picked from commit 9ebc58fd810cdfac1c9b790aace9922497fdfa5b)
=> Update ProgressOnderwijsUtils.AspNetCore to .NET Core 3.0

src/ProgressOnderwijsUtils/Utils.cs, test/ProgressOnderwijsUtils.Tests/RetryDelayChooserTest.cs
=> Improve retry-delay-chooser test

src/ProgressOnderwijsUtils/DisposableExtensions.cs, src/ProgressOnderwijsUtils/Utils.cs
=> Remove dead code

src/ProgressOnderwijsUtils/Utils.cs, test/ProgressOnderwijsUtils.Tests/ToFixedPointTest.cs
=> Some easy tweaks to fixpoint code

ProgressOnderwijsUtils.sln, src/Common.props, src/NugetPackagesCommon.props, src/ProgressOnderwijsUtils.AspNetCore/ProgressOnderwijsUtils.AspNetCore.csproj, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Tests/ProgressOnderwijsUtils.Tests.csproj, tools/ProgressOnderwijsUtilsBenchmarks/ProgressOnderwijsUtilsBenchmarks.csproj
=> Use snupkg format

src/Common.props, src/NugetPackagesCommon.props, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SingleSignOn/SsoAttributes.cs, src/ProgressOnderwijsUtils/SingleSignOn/SsoProcessor.cs, test/ProgressOnderwijsUtils.Tests/PocoPropertyConvertibleLoaderTest.cs, tools/ProgressOnderwijsUtilsBenchmarks/ArrayBuilderBenchmark.cs
Volgens mij doen we gewoon alles volgens heb boekje, dus ik snap niet waarom dit stuk is...:
https://github.com/dotnet/sourcelink#using-source-link-in-net-projects
=> Fiddle with source link, because that seems broken

src/ProgressOnderwijsUtils/Collections/RootedTree.cs, src/ProgressOnderwijsUtils/Collections/SList.cs, test/ProgressOnderwijsUtils.Tests/RootedTreeTest.cs
Om dit makkelijker te maken:
https://github.com/progressonderwijs/progress/pull/29987#discussion_r372308769
=> PreviousSibling + NextSibling implementatie

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
https://github.com/progressonderwijs/ProgressOnderwijsUtils/pull/388#issuecomment-580232361
Ik was net wat te laat ( ⚆ _ ⚆ )
=> bump version + edit releasenote

ProgressOnderwijsUtils.sln
Misschien kunnen er nog meer files worden verwijderd?
=> Verwijder onbestaande files uit de solution items.

src/ProgressOnderwijsUtils.Analyzers/ProgressOnderwijsUtils.Analyzers.csproj, test/ProgressOnderwijsUtils.Analyzers.Tests/ProgressOnderwijsUtils.Analyzers.Tests.csproj
This is what hopefully is missing - as taken from the VS template.
=> The analyzer inside the assembly is not found when importing the NuGet package.

src/ProgressOnderwijsUtils.Analyzers/ProgressOnderwijsUtils.Analyzers.csproj
=> Target netstandard2.0 for Visual Studio support

src/ProgressOnderwijsUtils/Data/CommandFactory.cs, src/ProgressOnderwijsUtils/Html/HtmlAttribute.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Tests/HtmlAttributesTest.cs
...to make it slightly easier to query the content of an HtmlFragment.
=> A few more tests and convenience methods

.github/workflows/codeql-analysis.yml
https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning
=> Probeer code scanning uit

src/ProgressOnderwijsUtils.AspNetCore/SecurityHeadersMiddlewareOptions.cs, src/ProgressOnderwijsUtils/Collections/FastArrayBuilder.cs, src/ProgressOnderwijsUtils/Data/CodeGenHelper.cs, src/ProgressOnderwijsUtils/Data/CommandFactory.cs, src/ProgressOnderwijsUtils/Data/DbDataReaderBase.cs, src/ProgressOnderwijsUtils/Data/PocoDataReader.cs, src/ProgressOnderwijsUtils/Data/SqlServerUtils.cs, src/ProgressOnderwijsUtils/Extensions/StringExtensions.cs, src/ProgressOnderwijsUtils/Extensions/XmlExtensions.cs, src/ProgressOnderwijsUtils/Html/HtmlAttribute.cs, src/ProgressOnderwijsUtils/Html/TagDescription.cs, src/ProgressOnderwijsUtils/NullableReferenceTypesHelpers.cs, test/ProgressOnderwijsUtils.Analyzers.Tests/DiagnosticHelper.cs, test/ProgressOnderwijsUtils.Tests/EnumerableExtensionsTests.cs, test/ProgressOnderwijsUtils.Tests/MaybeTests.cs, test/ProgressOnderwijsUtils.Tests/StringExtensionsTest.cs, test/ProgressOnderwijsUtils.Tests/TreeTest.cs, tools/ProgressOnderwijsUtilsBenchmarks/AlternativeArrayBuilders.cs
Most are correct nullability issues conceptually, but simply never reachable due to control flow.
=> Fix R# warnings

src/ProgressOnderwijsUtils/Data/ColumnOrdering.cs, src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs, src/ProgressOnderwijsUtils/RandomHelper.cs, src/ProgressOnderwijsUtils/Utils.cs
Replace with System.HashCode builder
prep for ORM record support.
=> Remove prime number generator

src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs, src/ProgressOnderwijsUtils/Data/SqlBatch.cs, src/ProgressOnderwijsUtils/Pocos/PocoProperties.cs, test/ProgressOnderwijsUtils.Tests/Data/PocoObjectMapperTest.cs
So records with non-nullable properties are workable
depends on <s>#471</s> and <s>#470</s>
=> Allow mapping by constructor args

src/ProgressOnderwijsUtils/Data/CascadedDelete.cs, test/ProgressOnderwijsUtils.Tests/Data/CascadedDeleteTest.cs
just reuse DatabaseDescription instead of reinventing it.
=> CascadedDelete faster and simpler

src/ProgressOnderwijsUtils/Data/CascadedDelete.cs, test/ProgressOnderwijsUtils.Tests/Data/CascadedDeleteTest.cs
Bij het maken van #477 viel me op dat er geen test was voor de cycle-detection.
Deze PR voegt dit toe, maar toen dacht ik - ik kan toch ook een zinvollere fout en veel eerder geven?  Nou, zo gedacht, zo geprobeerd.
Zou zeker fijner moeten zijn aan de consumer kant, maar nadeel is wel dat de code complexer is.
Is een niche debug help een beetje extra complexiteit waard?
=> "Better" cycle detect

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/TopologicalSort.cs, test/ProgressOnderwijsUtils.Tests/OrderByTopologyTest.cs
=> Cycle detect in topological sort

src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SchemaReflection/CheckConstraint.cs, src/ProgressOnderwijsUtils/SchemaReflection/DatabaseDescription.cs, src/ProgressOnderwijsUtils/SchemaReflection/DbColumnMetaData.cs, test/ProgressOnderwijsUtils.Tests/Data/DatabaseDescriptionTest.cs
Check constraints toegevoegd en columns uitgebreid met IsString en IsUnicode
=> Uitbreiden database description

ProgressOnderwijsUtils.sln.DotSettings, src/ProgressOnderwijsUtils.AspNetCore/ProgressOnderwijsUtils.AspNetCore.csproj, src/ProgressOnderwijsUtils.AspNetCore/SecurityHeadersMiddleware.cs, src/ProgressOnderwijsUtils.AspNetCore/SecurityHeadersMiddlewareOptions.cs
https://www.caniuse.com/?search=X-Frame-Options
https://www.caniuse.com/?search=X-XSS-Protection
=> Removed support for obsolete security headers

src/ProgressOnderwijsUtils/Html/HtmlFragment.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Tests/HtmlTests.cs
Wat moest er ook alweer gebeuren om hier een nieuwe versie van te pushen?
=> fix empty check

ProgressOnderwijsUtils.sln.DotSettings, src/ProgressOnderwijsUtils/Pocos/SmallBatchInsertImplementation.cs, src/ProgressOnderwijsUtils/XmlSerializableBase.cs
(reported as https://youtrack.jetbrains.com/issue/RSRP-483518 & https://youtrack.jetbrains.com/issue/RSRP-483519)
=> Suppress false warnings 

src/ProgressOnderwijsUtils/Data/CommandTimeout.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
Ik wil hier nog een paar stappen in maken, dus ga niet direct bumpen.
=> Avoid dependency on ValueUtils

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SchemaReflection/DatabaseDescription.cs, src/ProgressOnderwijsUtils/SchemaReflection/ForeignKeyLookup.cs, test/ProgressOnderwijsUtils.Tests/Data/DatabaseDescriptionTest.cs
=> Expose way of finding foreign keys by name

test/ProgressOnderwijsUtils.Tests/ToStringByMembersTest.cs
=> Verwijder overbodige white-space.

src/ProgressOnderwijsUtils.Analyzers/ProgressOnderwijsUtils.Analyzers.csproj, test/ProgressOnderwijsUtils.Analyzers.Tests/ProgressOnderwijsUtils.Analyzers.Tests.csproj
=> Aren't over-split nuget packages great.

src/ProgressOnderwijsUtils/Collections/RootedTree.cs, src/ProgressOnderwijsUtils/Data/CommandFactory.cs, src/ProgressOnderwijsUtils/Data/FieldMapping.cs, src/ProgressOnderwijsUtils/Data/ParameterizedSqlSubQueries.cs, src/ProgressOnderwijsUtils/Data/PocoDataReader.cs, src/ProgressOnderwijsUtils/Pocos/PocoBulkCopy.cs, src/ProgressOnderwijsUtils/ProcessRunner.cs, test/ProgressOnderwijsUtils.Tests/ArrayExtensionsTest.cs, test/ProgressOnderwijsUtils.Tests/OrderByColumnsTest.cs, test/ProgressOnderwijsUtils.Tests/SelfSanityCheck.cs, tools/ProgressOnderwijsUtilsBenchmarks/ArrayBuilderBenchmark.cs, tools/ProgressOnderwijsUtilsBenchmarks/MicroOrmBench/HandrolledAdoNetExecutor.cs
...this time also press Ctrl-Shift-S afterwards, unlike https://github.com/progressonderwijs/ProgressOnderwijsUtils/pull/608
=> Run solution wide code-cleanup

appveyor.yml
This reverts commit 226028e15015ccbeb7cac31efcbda4e28c07cb68.
=> Revert "Disable broken symbol publish"

src/ProgressOnderwijsUtils/ActionRetrier.cs, src/ProgressOnderwijsUtils/Collections/SortedSet.cs, src/ProgressOnderwijsUtils/Data/EFQueryResultTypeLooksLazy.cs, src/ProgressOnderwijsUtils/Data/FromDbValueConverter.cs, src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs, src/ProgressOnderwijsUtils/Data/SqlCommandDebugStringifier.cs, src/ProgressOnderwijsUtils/Extensions/TypeExtension.cs, src/ProgressOnderwijsUtils/Memoizer.cs, src/ProgressOnderwijsUtils/Pocos/ICopyable.cs, src/ProgressOnderwijsUtils/Pocos/MetaObjectPropertyMapping.cs, src/ProgressOnderwijsUtils/Pocos/SingleIdMapping.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/ReflectionLoadableClassHelper.cs, src/ProgressOnderwijsUtils/ReflectionLoadedBaseClass.cs, src/ProgressOnderwijsUtils/ResourceStore.cs, src/ProgressOnderwijsUtils/RetryDelayChooser.cs, src/ProgressOnderwijsUtils/StringMeasurer.cs, test/ProgressOnderwijsUtils.Tests/ActionRetrierTest.cs, test/ProgressOnderwijsUtils.Tests/Collections/IntOrdering.cs, test/ProgressOnderwijsUtils.Tests/Collections/SortedSetTest.cs, test/ProgressOnderwijsUtils.Tests/Collections/SortedSet_CountAndMoveDistinctValuesToFrontTest.cs, test/ProgressOnderwijsUtils.Tests/Collections/SortedSet_IdxAfterLastLtNode_Test.cs, test/ProgressOnderwijsUtils.Tests/Collections/SortedSet_MergeSetsTest.cs, test/ProgressOnderwijsUtils.Tests/Data/EFQueryResultTypeLooksLazyTest.cs, test/ProgressOnderwijsUtils.Tests/PropertyMappingTest.cs, test/ProgressOnderwijsUtils.Tests/StringMeasurerTest.cs
Mostly to save on compile time.
=> Move a bunch of utils out of progress

appveyor.yml
see also: https://www.appveyor.com/updates/
=> Let's try a newer appveyor image

src/ProgressOnderwijsUtils/Data/PooledSqlCommandAllocator.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, tools/ProgressOnderwijsUtilsBenchmarks/BenchmarkProgram.cs
=> Enabled OptimizedParameterBinding and bump SqlClient

appveyor.yml
- aka sign in here https://www.nuget.org/account/apikeys
- click regenerate
- copy-paste here https://ci.appveyor.com/tools/encrypt
- copy paste encrypted value right back here...
=> Regenerate expired API key.

src/ProgressOnderwijsUtils/Collections/Maybe.cs, src/ProgressOnderwijsUtils/Collections/MaybeExtensions.cs, src/ProgressOnderwijsUtils/Pocos/SmallBatchInsertImplementation.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/ReflectionLoadableClassHelper.cs, src/ProgressOnderwijsUtils/ReflectionLoadedBaseClass.cs, test/ProgressOnderwijsUtils.Analyzers.Tests/ProgressOnderwijsUtils.Analyzers.Tests.csproj, test/ProgressOnderwijsUtils.Tests/MaybeTests.cs, test/ProgressOnderwijsUtils.Tests/ProgressOnderwijsUtils.Tests.csproj
It's a little too easy as-is to discard away essential stuff, hiding bugs.
Make such discards explicit via DiscardValue.
=> Avoid accidental loss of maybe-OK

src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs, test/ProgressOnderwijsUtils.Tests/Data/PocoPropertyConvertibleLoaderTest.cs
Change api of ReadAllFieldsExpression to allow arbitrary MemberInfos, so I *can* use fields too, so I can easily define a tuple-reader too.
And while I'm at it, support NotMappedAttribute as EF does, because that's easier than fiddling with `internal`.
=> Prepare for field-based readers

src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs, src/ProgressOnderwijsUtils/Data/SqlBatch.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Tests/Data/PocoObjectMapperTest.cs
good enough like this?
It's fairly straightforward, but seems to work fine...
- Depends on #672
=> Implement a simplistic tuple reader

src/ProgressOnderwijsUtils/Pocos/BulkInsertTarget.cs, test/ProgressOnderwijsUtils.Tests/Data/PocoBulkCopyTest.cs
...and cleanup the test file in general.
e50925cffac883a77a34ae1861e7fcc2ed9774c2 contains the added test.
=> Add test that inserting into a computed column crashes

src/ProgressOnderwijsUtils/Collections/Tree.cs, src/ProgressOnderwijsUtils/Data/CodeGenHelper.cs, src/ProgressOnderwijsUtils/Data/SqlParameterComponent.cs, src/ProgressOnderwijsUtils/Extensions/DictionaryExtensions.cs, src/ProgressOnderwijsUtils/Extensions/TypeExtension.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SchemaReflection/DatabaseDescription.cs, test/ProgressOnderwijsUtils.Tests/DictionaryExtensionsTests.cs, test/ProgressOnderwijsUtils.Tests/DistinctArrayTest.cs, test/ProgressOnderwijsUtils.Tests/OrderByTopologyTest.cs, test/ProgressOnderwijsUtils.Tests/TreeTest.cs
- remove duplicates and almost-duplicates of GetValueOrDefault
- Address roslyn+R# warnings.
- bump version
=> Cleanup code

ProgressOnderwijsUtils.sln, src/ProgressOnderwijsUtils.SeleniumWebDriverPool/ProgressOnderwijsUtils.SeleniumWebDriverPool.csproj, src/ProgressOnderwijsUtils.SeleniumWebDriverPool/WebDriverPool.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Tests/RandomHelperTest.cs, test/ProgressOnderwijsUtils.Tests/UtilsTest.cs, tools/ProgressOnderwijsUtilsBenchmarks/ArrayBuilderBenchmark.cs, tools/ProgressOnderwijsUtilsBenchmarks/ProgressOnderwijsUtilsBenchmarks.csproj
Aim: to avoid taking unnecessary dependencies.
=> Remove morelinq dependency and split WebDriverPool into its own package.

src/ProgressOnderwijsUtils/Html/HtmlClassAttribute.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
-  issue: #729
Het moet mogelijk zijn om null op te kunnen geven in sommige gevallen. 
zoals bij ? :
=> Make CssClasses nullable

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SchemaReflection/DbColumnMetaData.cs, src/ProgressOnderwijsUtils/SchemaReflection/SqlSystemTypeIdExtensions.cs
This is useful for PocoGenerator.
=> Add support for specifying more sql-level metadata

tools/ParseCSSFile.linq
also makes a reference if an object already excists in its namespace
=> Add a method for gaining the C# file output string

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/XmlSerializableBase.cs
https://github.com/progressonderwijs/progress/pull/50168
https://uocg.fogbugz.com/f/cases/44140/STAP-Vraag-Bewijs-van-deelname
All in line with the .Net XML serialization API.
=> Added explicit namespaces to XML serialization plus added extension methods to stringify a XDocument with XML declaration.

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/XmlSerializableBase.cs
Reverts progressonderwijs/ProgressOnderwijsUtils#758
=> Revert "Added explicit namespaces to XML serialization plus added extension methods to stringify a XDocument with XML declaration."

src/ProgressOnderwijsUtils/Html/HtmlAttribute.cs, src/ProgressOnderwijsUtils/Html/HtmlClassAttribute.cs, test/ProgressOnderwijsUtils.Tests/HtmlAttributesTest.cs
- base PR: https://github.com/progressonderwijs/ProgressOnderwijsUtils/issues/763
- Aim: reduce diff size of https://github.com/progressonderwijs/ProgressOnderwijsUtils/compare/master...maartje/HasClassWithCssParam?expand=1
- new diff would be: https://github.com/progressonderwijs/ProgressOnderwijsUtils/compare/master...eamon/ReduceDiffSize?expand=1
smaller diff ;-)
=> reduce diff size: move method

src/ProgressOnderwijsUtils/Html/HtmlAttribute.cs, src/ProgressOnderwijsUtils/Html/HtmlClassAttribute.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Tests/HtmlAttributesTest.cs, test/ProgressOnderwijsUtils.Tests/HtmlToStringApprovals.cs
CssClass ClassName is now also nullable
=> HasClass with CssClass param 

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
(bumps waren al in allemaal dependabot voorloop PRs)
=> Bump to .net 7

test/ProgressOnderwijsUtils.Tests/NullablityTestClass.cs, tools/ProgressOnderwijsUtilsBenchmarks/BenchmarkProgram.cs, tools/ProgressOnderwijsUtilsBenchmarks/NullabilityBenchmark.cs
=> nog wat ideeen

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/XmlSerializableBase.cs
See also https://github.com/progressonderwijs/ProgressOnderwijsUtils/pull/759
=> Added XmlSerializerNamespaces option to the XML-serialization helpers that will be passed to the .Net implementation.

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
=> Release new version with nuget bumps

src/ProgressOnderwijsUtils.SeleniumWebDriverPool/ProgressOnderwijsUtils.SeleniumWebDriverPool.csproj, src/ProgressOnderwijsUtils.SeleniumWebDriverPool/WebDriverPool.cs
=> Remove obsolete method

src/ProgressOnderwijsUtils/Data/ParameterizedSqlExtensions.cs, src/ProgressOnderwijsUtils/Data/SqlTimeoutDetection.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
...and inline barely used overloads with obvious alternatives
- depends on #807
=> Remove obsolete unused method

src/ProgressOnderwijsUtils/Data/CascadedDelete.cs, src/ProgressOnderwijsUtils/Data/PocoDataReader.cs, src/ProgressOnderwijsUtils/Data/SqlParameterComponent.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
(with a few minor code cleanups as suggested by warnings)
- depends on #808
=> Bump nuget package version

src/ProgressOnderwijsUtils.AspNetCore/ProgressOnderwijsUtils.AspNetCore.csproj, src/ProgressOnderwijsUtils.AspNetCore/SecurityHeadersMiddleware.cs, src/ProgressOnderwijsUtils.AspNetCore/SecurityHeadersMiddlewareOptions.cs
Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy
Internal issue: https://github.com/progressonderwijs/progress/issues/50548
=> Add support for Permissions-Policy

appveyor.yml
=> Regenerate api-key

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/RequiredFields/NonNullableFieldVerifier.cs, src/ProgressOnderwijsUtils/RequiredFields/NonNullableFieldVerifier0.cs, src/ProgressOnderwijsUtils/RequiredFields/NonNullableFieldVerifier1.cs, src/ProgressOnderwijsUtils/RequiredFields/NonNullableFieldVerifier2.cs, src/ProgressOnderwijsUtils/RequiredFields/NonNullableFieldVerifier3.cs, src/ProgressOnderwijsUtils/RequiredFields/NonNullableFieldVerifier4.cs, test/ProgressOnderwijsUtils.Tests/Data/PocoObjectMapperTest.cs, test/ProgressOnderwijsUtils.Tests/NonNullableNullabilityCheck.cs
- https://github.com/progressonderwijs/progress/pull/52296
- de excepion message is aangepast (c# friendly name)
- test toegevoegd die de exception message valideert
=> Nullablility verifier optimalizations (o.a. excepion message)

src/ProgressOnderwijsUtils/Extensions/UriExtensions.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
...so I can use it in progress.
(was in packager)
=> Move DeleteLocalFolderRecursivelyAndWait to utils

src/ProgressOnderwijsUtils/Extensions/UriExtensions.cs
Let's hope they don't restore the old behavior with similarly little notice...
As noted by @chrarnoldus in #823
=> Note that this isn't necessary on modern versions of windows.

src/ProgressOnderwijsUtils/SchemaReflection/DbObjectIndex.cs, src/ProgressOnderwijsUtils/SchemaReflection/RawDatabaseDescription.cs, src/ProgressOnderwijsUtils/SchemaReflection/SqlCompressionTypeExtensions.cs, src/ProgressOnderwijsUtils/SchemaReflection/SqlIndexTypeExtensions.cs
TODO: include the raw index schema info in the more convenient DatabaseDescription.
- https://github.com/progressonderwijs/progress/issues/53103
=> Include information about indexes

src/ProgressOnderwijsUtils/GitExe.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
I'll need this to create a GitHub PR from the worktree.
=> Added optional branch to git worktree

src/ProgressOnderwijsUtils/RequiredFields/NonNullableFieldVerifier.cs, src/ProgressOnderwijsUtils/RequiredFields/NonNullableFieldVerifier4.cs, src/ProgressOnderwijsUtils/RequiredFields/NonNullableFieldVerifier5.cs, test/ProgressOnderwijsUtils.Tests/NonNullableNullabilityCheck.cs, tools/ProgressOnderwijsUtilsBenchmarks/NullabilityBenchmark.cs
- https://github.com/progressonderwijs/ProgressOnderwijsUtils/issues/773
We've experimented with a bunch of nullability checkers; but we've settled on v4.  That means it's time to clean up the experiments.
As prep: a  few renames; the old non-numbered one to v5; and copy of v4 to non-numbered.
=> prep cleanup verifiers

src/ProgressOnderwijsUtils/RequiredFields/NonNullableFieldVerifier.cs
- depends on #839 
- issue #773
=> make implementation more readable

test/ProgressOnderwijsUtils.Tests/NonNullableNullabilityCheck.cs
- depends on  #842
- issue #773 
- Add a bunch of tests for other potential corner cases
- (sometimes adapted from tests for previous versions of verifiers from  #841)
=> Improve tests

src/ProgressOnderwijsUtils/Html/HtmlSpec.Generated.cs, test/ProgressOnderwijsUtils.Tests/.gitignore, test/ProgressOnderwijsUtils.Tests/HtmlDslGenerator.cs
https://github.com/progressonderwijs/progress/issues/54350
=> Allow rerunning the dsl generator locally without hitting remote servers all the time

test/ProgressOnderwijsUtils.Tests/Data/ReadJsonTest.ReadJson_can_read_all_known_used_column_types_from_the_db.approved.txt, test/ProgressOnderwijsUtils.Tests/Data/ReadJsonTest.cs
- Nawerk https://github.com/progressonderwijs/ProgressOnderwijsUtils/pull/856
- Gevonden via deze random fail https://ci.appveyor.com/project/progressonderwijs/progressonderwijsutils/builds/47281313
=> de test moet deterministisch zijn, want er is een approval.

src/ProgressOnderwijsUtils/Pocos/PocoProperties.cs, src/ProgressOnderwijsUtils/Pocos/PocoProperty.cs, src/ProgressOnderwijsUtils/Pocos/PocoUtils.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Tests/PocoUtilsTest.cs
Voor nawerk gerelateerd aan https://github.com/progressonderwijs/progress/pull/54432
=> Expose nullability in poco utils

src/ProgressOnderwijsUtils/Data/CommandFactory.cs, src/ProgressOnderwijsUtils/Data/ParameterValuesForDebuggingExtension.cs, src/ProgressOnderwijsUtils/Data/ParameterizedSql.cs, src/ProgressOnderwijsUtils/Data/SqlParameterComponent.cs, src/ProgressOnderwijsUtils/Html/HtmlToCSharp.cs, src/ProgressOnderwijsUtils/Html/HtmlToStringExtensions.cs
zodat ik niet constant offset+length mee moet geven.
=> Use span internally

src/ProgressOnderwijsUtils/Data/SqlServerUtils.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SchemaReflection/DatabaseDefinitionScripter.cs, src/ProgressOnderwijsUtils/SchemaReflection/IDbColumn.cs
Fix the script so it delivers valid sql, which can be used to created an empty database.
=> Fix sql script

src/ProgressOnderwijsUtils/Data/SqlServerUtils.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
introduced in https://github.com/progressonderwijs/ProgressOnderwijsUtils/pull/894
=> Fix regression in sql prettify

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SchemaReflection/DatabaseDefinitionScripter.cs
undo https://github.com/progressonderwijs/ProgressOnderwijsUtils/pull/894/commits/1cda5190d85a629f8fee328833f206c57e6d4317
=> Restore collation for computed columns

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SchemaReflection/DatabaseDefinitionScripter.cs, src/ProgressOnderwijsUtils/SchemaReflection/RawDatabaseDescription.cs
Extracted existing code to create tables/indexes/triggers etc into methods, to be able to call the methods not per tabel (as is currently used for the database approval) but first create the tables and then apply the constraints/indexes etc. Also added the creation of schemas.
=> Generate SQL to create a database

src/ProgressOnderwijsUtils.Analyzers/ProgressOnderwijsUtils.Analyzers.csproj, test/ProgressOnderwijsUtils.Analyzers.Tests/ProgressOnderwijsUtils.Analyzers.Tests.csproj
Per stuk upgraden werkt niet, daarom hier allemaal tegelijk
In plaats van 
https://github.com/progressonderwijs/ProgressOnderwijsUtils/pull/899
https://github.com/progressonderwijs/ProgressOnderwijsUtils/pull/900
https://github.com/progressonderwijs/ProgressOnderwijsUtils/pull/901
=> Alles tegelijk naar 4.7.0

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/RandomHelper.cs, test/ProgressOnderwijsUtils.Tests/RandomHelperTest.cs, tools/ProgressOnderwijsUtilsBenchmarks/BenchmarkProgram.cs, tools/ProgressOnderwijsUtilsBenchmarks/RandomHelperBenchmark.cs
(use more convenient optimal paths that have been included in recent .net versions)
=> Optimize RandomHelper

src/ProgressOnderwijsUtils/RandomHelper.cs, test/ProgressOnderwijsUtils.Tests/RandomHelperTest.cs
=> Better RandomHelper tests

src/ProgressOnderwijsUtils/Data/SqlParameterComponent.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Tests/Data/TableValuedParameterTest.cs
Relevant for lijst-key's that are Iban's
=> Support AutomaticValueConverters in table-valued-type parameters

src/ProgressOnderwijsUtils/Data/CascadedDelete.cs, src/ProgressOnderwijsUtils/Data/ParameterizedSql.cs, src/ProgressOnderwijsUtils/Data/ParameterizedSqlExtensions.cs, src/ProgressOnderwijsUtils/Data/ParameterizedSqlSubQueries.cs, src/ProgressOnderwijsUtils/Data/SqlParameterComponent.cs, src/ProgressOnderwijsUtils/Pocos/BulkInsertTarget.cs, src/ProgressOnderwijsUtils/Pocos/PocoProperty.cs, src/ProgressOnderwijsUtils/Pocos/SmallBatchInsertImplementation.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SchemaReflection/DatabaseDescription.cs, src/ProgressOnderwijsUtils/SchemaReflection/DbColumnMetaData.cs, src/ProgressOnderwijsUtils/SchemaReflection/DbQualifiedNameUtils.cs, src/ProgressOnderwijsUtils/SchemaReflection/IDbColumn.cs, test/ProgressOnderwijsUtils.Tests/Data/ConcatenateSqlTest.cs, test/ProgressOnderwijsUtils.Tests/Data/DatabaseDescriptionTest.cs, test/ProgressOnderwijsUtils.Tests/Data/ParameterizedSqlTest.cs, test/ProgressOnderwijsUtils.Tests/Data/TestSqlParameterComponent.cs
And add a few safer alternatives that nevertheless allow some dynamic sql generation without the risks of sql injection.
Bumps version to v99.
(Previously: #921)
- issue: https://github.com/progressonderwijs/progress/issues/43386
- issue: https://github.com/progressonderwijs/progress/issues/42551
=> Rename CreateDynamic => RawSql_PotentialForSqlInjection

src/ProgressOnderwijsUtils.SeleniumWebDriverPool/ProgressOnderwijsUtils.SeleniumWebDriverPool.csproj, src/ProgressOnderwijsUtils.SeleniumWebDriverPool/WebDriverPool.cs
Na een nieuwe versie van Selenium lijkt het erop dat de driver zelfstandig opstart op een later moment en dat daarom deze eerste Start nog geen driverServicePath bevat.
Dit was optioneel in vorige versies
- Issue: #935
=> Selenium geeft foutmelding

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- https://github.com/progressonderwijs/progress/issues/58549
=> Bump dependencies

src/ProgressOnderwijsUtils/Collections/SortedSet.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, test/ProgressOnderwijsUtils.Tests/Collections/SortedSetTest.cs, test/ProgressOnderwijsUtils.Tests/Collections/SortedSet_IdxAfterLastLtNode_Test.cs, test/ProgressOnderwijsUtils.Tests/Collections/SortedSet_MergeSetsTest.cs
- https://github.com/progressonderwijs/progress/issues/58621
=> Write algorithms for 2-way merge and more efficient subset detection

test/ProgressOnderwijsUtils.Analyzers.Tests/ProgressOnderwijsUtils.Analyzers.Tests.csproj, test/ProgressOnderwijsUtils.Tests/ProcessRunnerTest.cs, test/ProgressOnderwijsUtils.Tests/ProgressOnderwijsUtils.Tests.csproj
tests met await aangepast omdat een xunit analyzer anders mekkert.
=> Bump xunit

src/ProgressOnderwijsUtils.Analyzers/RedundantAssertNotNullAnalyzer.cs
=> Fix warning

src/ProgressOnderwijsUtils.Analyzers/RedundantAssertNotNullAnalyzer.cs, src/ProgressOnderwijsUtils/Data/ColumnDefinition.cs, src/ProgressOnderwijsUtils/Data/PocoDataReader.cs, src/ProgressOnderwijsUtils/Pocos/SmallBatchInsertImplementation.cs
=> Weg legacy uitzondering voor identity columns

src/ProgressOnderwijsUtils/Data/CascadedDelete.cs, src/ProgressOnderwijsUtils/Data/ParameterizedSql.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SchemaReflection/DatabaseDescription.cs, test/ProgressOnderwijsUtils.Tests/Data/CascadedDeleteTest.cs, test/ProgressOnderwijsUtils.Tests/ProcessRunnerTest.cs
- https://github.com/progressonderwijs/progress/issues/60234
=> Cascade delete fix

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/SchemaReflection/IDbColumn.cs
- https://github.com/progressonderwijs/progress/issues/60555
Fix for https://github.com/progressonderwijs/progress/pull/60759
=> Static row-version is not computed.

src/ProgressOnderwijsUtils/Data/ParameterizedSql.cs, test/ProgressOnderwijsUtils.Tests/Data/ParameterizedSqlTest.cs, test/ProgressOnderwijsUtils.Tests/PocoUtilsTest.cs, tools/ProgressOnderwijsUtilsBenchmarks/MicroOrmBench/ExampleObject.cs, tools/ProgressOnderwijsUtilsBenchmarks/MicroOrmBench/WideExampleObject.cs
- Mogelijk behulpzaam voor https://github.com/progressonderwijs/progress/pull/61552
- Wat vind je van de naamgeving?  Moeten UnescapedSqlIdentifier of AssertQualifiedSqlIdentifier nog anders?
=> Add safe to-qualified-name helper

src/ProgressOnderwijsUtils/Extensions/TreeExtensions.cs, src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj, src/ProgressOnderwijsUtils/Win32/VirusScan.cs, test/ProgressOnderwijsUtils.Tests/Win32/VirusScanTest.cs
- #https://github.com/progressonderwijs/progress/issues/62775
=> Do not crash on a virus scan of an empty file.

src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- Alvast klein stapje richting .net 9 upgrade https://github.com/progressonderwijs/progress/issues/60929
- maar eigenlijk nav. opmerking @chrarnoldus in
- https://github.com/progressonderwijs/ProgressOnderwijsUtils/pull/1096
- https://github.com/progressonderwijs/ProgressOnderwijsUtils/pull/1097
=> Weg met meer meuk
