progressonderwijs/ProgressOnderwijsUtils

- src/ProgressOnderwijsUtils/Collections/RootedTree.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtilsTests/RootedTreeTest.cs
Hiermee kunnen we straks redelijk eenvoudig een node veranderen, toevoegen of verwijderen.
Zie ook de test case als voorbeeld hiervoor.
> RootedTree.ReplaceSubTree gemaakt om een (Rooted)Tree mee te kunnen manipuleren.

- src/ProgressOnderwijsUtils/Data/SqlParameterComponent.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtilsTests/TableValuedParameterTest.cs
- test/ProgressOnderwijsUtilsTests/TransactedLocalConnection.cs
Zodat we de scripts ook kunnen draaien straks in de SqlMigrator die zijn eigen transactie heeft.
> Haal de specifieke transactie uit het TableValuedTypeDefinitionScripts.

- src/ProgressOnderwijsUtils/ResourceStore.cs
In PNet, ResourceStore is always used in a non-null fashion. Requiring a bunch of null checks is impractical; better to check once here.
Alternative API suggestions welcome.
> resource store is non null

- ProgressOnderwijsUtils.sln.DotSettings
- src/ProgressOnderwijsUtils/Data/CommandFactory.cs
- src/ProgressOnderwijsUtils/Data/MetaObjectDataReader.cs
- src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs
- src/ProgressOnderwijsUtils/Data/SqlCommandDebugStringifier.cs
- src/ProgressOnderwijsUtils/Data/SqlCommandTracer.cs
- src/ProgressOnderwijsUtils/MetaObject/MetaObjectBulkCopy.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtils.Tests/DistinctArrayTest.cs
- test/ProgressOnderwijsUtils.Tests/TransactedLocalConnection.cs
In particular, also trace bulk copy duration+number of rows inserted.
Also reduce the api size, and include elapsed time in addition to sql time.
This will cause some breaking changes in pnet.
> Improve SqlCommandTracer

- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- src/ProgressOnderwijsUtils/SingleSignOn/SsoProcessor.cs
Example:
```xml
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_280dea7f76d83385651ab0aef8a12c6eb26532302cd580ce955ff0b2dcd3" Version="2.0" IssueInstant="2018-03-06T13:32:27Z" Destination="https://progresswww.nl/surff/sso/post/" InResponseTo="bla">
<saml:Issuer>https://sa-gw.surfconext.nl/authentication/metadata</saml:Issuer>
<samlp:Status>
<samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Responder">
<samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:NoAuthnContext" />
</samlp:StatusCode>
</samlp:Status>
</samlp:Response>
```
> Fix crash SsoProcessor.GetAssertion when multiple StatusCodes are present

- src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs
except for the (hopefully trivial) first commit, these are local refactorings, and replacing Expression.Compile with CompileFast *should* be safe.
> Minor cleanups

- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- src/ProgressOnderwijsUtils/SingleSignOn/SsoAttributes.cs
- src/ProgressOnderwijsUtils/SingleSignOn/SsoProcessor.cs
We weigeren requests die te oud zijn, echter kan AuthnInstant ver in het verleden liggen omdat je niet altijd je wachtwoord opnieuw hoeft in te vullen, dus IssueInstant is beter, denk ik.
> Replace AuthnInstant in SsoAttributes with IssueInstant

- src/ProgressOnderwijsUtils/Data/ParameterizedSql.cs
- src/ProgressOnderwijsUtils/Data/QueryTableValuedParameterComponent.cs
- src/ProgressOnderwijsUtils/Data/SqlParameterComponent.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtils.Tests/TableValuedParameterTest.cs
- tools/ProgressOnderwijsUtilsBenchmarks/ProgressOnderwijsUtilsBenchmarks.csproj
This is not yet the "reliably fast" solution that uses a roslyn analyser to enforce array-ness and uses temp tables instead of TVPs, but it'll work in many cases and shouldn't harm.
> Initial exception for singleton tvps

- src/ProgressOnderwijsUtils/Data/QueryTableValuedParameterComponent.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
… except now use `top` to really hint at the cardinality.
This is likely causing test timeouts in progress, so I'm going to merge this quickly.
> Partially restore length token for query-plan specialization

- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- src/ProgressOnderwijsUtils/RetryDelayChooser.cs
- test/ProgressOnderwijsUtils.Tests/RetryDelayChooserTest.cs
Essentially: ramp more aggressively by default, and recover more quickly too; but have the half-life configurable.
> Better retry delay chooser

- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- src/ProgressOnderwijsUtils/SingleSignOn/AuthnRequest.cs
HTTP-Redirect isn't actually a valid value here (https://stackoverflow.com/a/2239909). This value refers to the method used to send the response and not the request. (which makes sense, because you can only interpret it after you have already received the request)
> Fix AuthnRequest ProtocolBinding again

- src/ProgressOnderwijsUtils/Data/CascadedDelete.cs
- src/ProgressOnderwijsUtils/Data/FieldMapping.cs
- src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs
- src/ProgressOnderwijsUtils/MetaObject/MetaObjectBulkCopy.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtils.Tests/MetaObjectBulkCopyTest.cs
This is now possible because we can filter out the read-only db-columns.
> Set the default field-mapping to exact-match for the bulk-copies.

- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
In some cases, the current version works, but in others there are assembly loading issues.
So until haf/DotNetZip.Semverd#152 is fixed, let's downgrade.
> Downgrade DotNetZip

- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
So the DotNetZip warning is hopefullly fixed.
> Bump dependencies

- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- src/ProgressOnderwijsUtils/SqlErrorParser.cs
- test/ProgressOnderwijsUtils.Tests/SqlErrorParserTest.cs
I want to use this in sql migrations in pnet
> Tweak the SqlErrorParser api to make it more usable

- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
So https://github.com/progressonderwijs/progress/pull/23867 becomes mergable
Previously #247 
Probably best not to wait too long for this one because https://github.com/progressonderwijs/progress/pull/23867 has the promise of attracting a bunch of boring but time-consuming mergeconflicts
> Bump version

- src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs
- src/ProgressOnderwijsUtils/MetaObject/MetaInfo.cs
- src/ProgressOnderwijsUtils/MetaObject/MetaObject.cs
- src/ProgressOnderwijsUtils/MetaObject/MetaProperty.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- tools/ProgressOnderwijsUtilsBenchmarks/MicroOrmBench/Program.cs
This is motivated by the hope to make it a little easier to implement something like the value conversion, and as it happens it's no longer useful to inline the array construction during reader extraction, so removing the special case isn't hurting perf notably either.
> Simplify (and while at it, optimize) some parts of ParameterizedSqlObjectMapper

- src/ProgressOnderwijsUtils/Data/FromDbValueConverter.cs
- src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs
- src/ProgressOnderwijsUtils/Extensions/DictionaryExtensions.cs
- src/ProgressOnderwijsUtils/MetaObject/IMetaObjectPropertyConvertible.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtils.Tests/Data/TrivialConvertibleValue.cs
- test/ProgressOnderwijsUtils.Tests/FromDbValueConverterTest.cs
- test/ProgressOnderwijsUtils.Tests/MetaObjectPropertyLoaderTest.cs
This is a little dubious, since it means there are places in the code that are converting multiple times, but it's existing behavior in pnet.
> Allow FromDbValueConverter to accept values that were already in code format.

- src/ProgressOnderwijsUtils/Data/FromDbValueConverter.cs
- test/ProgressOnderwijsUtils.Tests/FromDbValueConverterTest.cs
This locally solves all failing test cases we have here: http://pcjenkins2015:8080/job/BuildTest-PullRequest/59814
> Support casting from null to IMetaObjectPropertyConverter types even with DynamicCast

- src/ProgressOnderwijsUtils/Collections/Maybe.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- src/ProgressOnderwijsUtils/Utils.cs
- test/ProgressOnderwijsUtils.Tests/MaybeTests.cs
- test/ProgressOnderwijsUtils.Tests/UtilsTest.cs
Aim: to make debugging failure cases easier, particularly when the cleanup code can fail too.
> Convenient try with cleanup wrapper

- src/ProgressOnderwijsUtils/Html/HtmlFragment.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtils.Tests/HtmlTests.cs
It may be content-less in browsers, but we still want to see it.
> Fix support for  html5 template parsing

- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- src/ProgressOnderwijsUtils/SchemaReflection/DatabaseDescription.cs
I've made a small banchmark between the former version only loading tables and this version also loading views:
```
using var conn = new Microsoft.Data.SqlClient.SqlConnection("Data Source=localhost;Initial Catalog=odsuvhlocal;Integrated Security=True;");
conn.Open();
var sw = System.Diagnostics.Stopwatch.StartNew();
var took = Enumerable.Range(0, 11)
.Select(i => {
sw.Restart();
var db = DatabaseDescription.LoadFromSchemaTables(conn);
return sw.ElapsedMilliseconds;
})
.Average();
ProgressLocalFontys:    40 ms   =>  40 ms
odsuvhlocal:            50 ms   =>  60 ms
```
> Add views to the database description.

- src/ProgressOnderwijsUtils/Collections/Tree.cs
- src/ProgressOnderwijsUtils/Data/ColumnSort.cs
- src/ProgressOnderwijsUtils/Data/OrderByColumns.cs
- src/ProgressOnderwijsUtils/Extensions/StringUtils.cs
- src/ProgressOnderwijsUtils/PnetNullableExtensions.cs
- src/ProgressOnderwijsUtils/Pocos/PocoUtils.cs
- src/ProgressOnderwijsUtils/Utils.cs
- src/ProgressOnderwijsUtils/XmlSerializableBase.cs
- test/ProgressOnderwijsUtils.Tests/OrderByColumnsTest.cs
- test/ProgressOnderwijsUtils.Tests/SortColumnTest.cs
- test/ProgressOnderwijsUtils.Tests/StringExtensionsTest.cs
- test/ProgressOnderwijsUtils.Tests/TreeTest.cs
- test/ProgressOnderwijsUtils.Tests/UtilsTest.cs
- mostly remove dead code whereby dead means "only used by its own tests, and implausible to be useful in the future"
- Simplify OrderByColumns.
- Some really minor breakign changes like a method rename; a removal of `.ColumnCount` because you can do `.Columns.Length`  (I intend to bump the major version in followup PR, but if I do that here, I'll implicitly publish these pointless changes, and I'd rather do some real work here too.)
> Various utils cleanups

- src/ProgressOnderwijsUtils/Collections/CachedTreeBuilder.cs
- test/ProgressOnderwijsUtils.Tests/TreeTest.cs
In particularly, less GC pressure. because only one smallish stack, instead of 2 stacks, one of which with a max-size that's covers all tree nodes, and additionally no need to collect tree kids separately from the tree kid array.
<s>Includes  #344, #346</s>
> Optimize recursive tree building

- src/ProgressOnderwijsUtils/DistinctArray.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtils.Tests/DistinctArrayTest.cs
Why reference based?  Well, it's really simple, it's fast, and with value-based equality you need to answer annoyingly tricky questions about which comparer to use.
> Allow straightforward reference-based equality for DistinctArray's.

- src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs
- src/ProgressOnderwijsUtils/RandomHelper.cs
- test/ProgressOnderwijsUtils.Tests/RandomHelperTest.cs
Zonder expliciete seed te hoeven meegeven. 
Dit is handig in testcode die database-records aanmaakt op basis van pseudo-random data. Daarbij is het belangrijk dat de gekozen seed niet elke keer hetzelfde is (om dubbele keys te voorkomen), maar je wilt niet handmatig elke keer een andere seed hard-coden.
----
Comments welcome.
> Rene/Factory method voor deterministische RandomHelper

- src/ProgressOnderwijsUtils/Collections/SList.cs
- src/ProgressOnderwijsUtils/Data/SqlServerUtils.cs
- src/ProgressOnderwijsUtils/DistinctArray.cs
- src/ProgressOnderwijsUtils/Extensions/StringExtensions.cs
- src/ProgressOnderwijsUtils/Extensions/StringUtils.cs
- src/ProgressOnderwijsUtils/Html/HtmlHelpers.cs
- src/ProgressOnderwijsUtils/ProcessRunner.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtils.Tests/SListTest.cs
- test/ProgressOnderwijsUtils.Tests/StringExtensionsTest.cs
- test/ProgressOnderwijsUtils.Tests/StringUtilsTest.cs
Motivatie: foutieve nullability tips in R# 2020 die veroorzaakt worden door annotaties hier mogelijk verhelpen.
Maar ik heb ook waar nodig wat test coverage verhoogd, en methods versimpeld waar ik te lui was om de hele api te testen, zodat code die ik in deze PR aanraak iig geen unused methods heeft (en hopelijk 100% method coverage).
Review bij commit zou redelijk moeten zijn.
> Various nullability-inspired cleanups & general version bump.

- src/ProgressOnderwijsUtils/Collections/ArrayComparer.cs
- src/ProgressOnderwijsUtils/Collections/MaybeExtensions.cs
- src/ProgressOnderwijsUtils/Collections/Tree.cs
- src/ProgressOnderwijsUtils/Data/ColumnSort.cs
- src/ProgressOnderwijsUtils/Data/OrderByColumns.cs
- src/ProgressOnderwijsUtils/Data/PocoDataReader.cs
- src/ProgressOnderwijsUtils/Utils.cs
- tools/ProgressOnderwijsUtilsBenchmarks/HtmlFragmentBenchmark.cs
There are some nasty annotations in mscorlib; and things like ComparisonComparer are rather impractical due to such issues.
Opening ProgressOnderwijsUtils and trying to fix nullability annotations is an exercise in seeing the limitations of nullability annotations in the first place.
I doubt we'll get all these both correct and useful (because of course we can get em correct simply by throwing on null all over the place, but that's not very useful).
If you care about nullability, there are plently more issues left, and trying to solve a few is a good excercise in the problems with the C# 8 approach to nullability; this isn't always easy, especially since mscorlib is poorly designed with nullability in mind.
> Some cleanups, workaround a few nullability issues.

- src/ProgressOnderwijsUtils.Analyzers/MustUseExpressionResultAnalyzer.cs
- src/ProgressOnderwijsUtils.Analyzers/ProgressOnderwijsUtils.Analyzers.csproj
- test/ProgressOnderwijsUtils.Analyzers.Tests/MustUseExpressionResultAnalyzerTest.cs
Note that the standard IDE0058 does _not_ implement this check.
> Also apply the POU1001 analyzer on expression body syntax.

- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- src/ProgressOnderwijsUtils/RandomHelper.cs
**Issue:** https://github.com/progressonderwijs/progress/issues/27686
**Motivation:** RandomHelper.Insecure() isn't used within solution Progress anymore. I think this method can be private.
> RandomHelper.Insecure() to private method

- src/ProgressOnderwijsUtils/Html/HtmlSpec.Generated.cs
No major changes.
(This is just copy-pasting the output of tools/ParseHtml5Spec.linq into the generated file)
> Regenerate from html spec

- src/ProgressOnderwijsUtils/DistinctArray.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- src/ProgressOnderwijsUtils/Utils.cs
Always invoke edgeLookup with distinct values, and promise that via type system too.
> Better api for TransitiveClosure

- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- src/ProgressOnderwijsUtils/SchemaReflection/DatabaseDescription.cs
- src/ProgressOnderwijsUtils/SchemaReflection/DmlTableTrigger.cs
- test/ProgressOnderwijsUtils.Tests/Data/DatabaseDescriptionTest.cs
So we can check whether a table has triggers within the CascadeDelete implementation, because the output clause depends on it.
Plus it may replace the check whether a table has a trigger or not within the dependant Progress repo.
> DML Table triggers are added to the DatabaseDescription

- src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs
- src/ProgressOnderwijsUtils/Data/SqlBatch.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- src/ProgressOnderwijsUtils/RsaStringSigner.cs
- test/ProgressOnderwijsUtils.Tests/Collections/SequenceEqualityComparerTest.cs
In particular: ITypeSqlCommand no longer returns something nullable, instead, the various implementations have finer-grained annotations.
> Nullability tweaks + fix warnings.

- src/ProgressOnderwijsUtils/Collections/Maybe.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtils.Tests/MaybeTests.cs
Voor situaties waar alleen een error kan optreden, maar geen returnvalue is
Ter illustratie: https://github.com/progressonderwijs/progress/pull/41802
> Maak een gebruiksvriendelijker alternatief voor maybe.either

- src/ProgressOnderwijsUtils/Collections/Maybe.cs
- src/ProgressOnderwijsUtils/Collections/MaybeExtensions.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
To prevent ```.WhenOk(_ => Unit.Value)``` of ```.WhenOk(_ => {})``` at the end of methods to confirm to return type
> Allow implicitly dropping the value component of Maybes

- src/ProgressOnderwijsUtils/Extensions/StringUtils.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtils.Tests/StringExtensionsTest.cs
- test/ProgressOnderwijsUtils.Tests/StringUtilsTest.cs
It seems that Studielink uses this extended unicode character as a ringle-S
> Add support for extended ringle-S (U+01E9E)

- src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs
- src/ProgressOnderwijsUtils/Data/SqlBatch.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
Same idea as https://github.com/progressonderwijs/progress/pull/42586
Make it possible to enforce always using return values
> return number of rows affected with out var instead of returnvalue

- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- src/ProgressOnderwijsUtils/SchemaReflection/SqlUnderlyingTypeInfo.cs
Viel op tijdens het maken van https://github.com/progressonderwijs/progress/pull/42826 - numeric heeft bij ons geen precision/scale.
> Script more precisions

- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- src/ProgressOnderwijsUtils/SchemaReflection/DbColumnMetaData.cs
- test/ProgressOnderwijsUtils.Tests/Data/DbColumnMetaDataTest.cs
DbColumnMetaData.Create is no longer in sync with ToSqlTypeName.ToSqlTypeName, after #600 
This means we can't round-trip certain types, and thus cannot create some temp tables, which is a problem.
This PR fixes the issue (#601 was prep)
> Fix DbColumnMetaData.Create 

- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- src/ProgressOnderwijsUtils/Utils.cs
- test/ProgressOnderwijsUtils.Tests/UtilsTest.cs
So that our services don't go down on an intermittent initialization failure.
> Avoid exception-catching behavior in Lazy

- src/ProgressOnderwijsUtils/Extensions/EnumerableExtensions.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- src/ProgressOnderwijsUtils/Utils.cs
- src/ProgressOnderwijsUtils/XmlCompression.cs
- test/ProgressOnderwijsUtils.Tests/Collections/ProjectingEqualityComparerTest.cs
- test/ProgressOnderwijsUtils.Tests/DistinctArrayTest.cs
- test/ProgressOnderwijsUtils.Tests/UtilsTest.cs
- tools/ProgressOnderwijsUtilsBenchmarks/ProgressOnderwijsUtilsBenchmarks.csproj
<span>Utils.Lazy returns Func&lt;&gt; intead of Lazy&lt;&gt; and no longer caches exceptions. Utils.Swap removed (can be replaced by tuple assignment). ToSet removed (can be replaced with Linq ToHashSet).</span>
Bumped version.
> Minor api tweaks

- src/ProgressOnderwijsUtils/Pocos/MetaObjectPropertyMapping.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtils.Tests/PropertyMappingTest.cs
So I can explicitly extract a single property type's mapping.
And expand test coverage
> Expand property mapper

- src/ProgressOnderwijsUtils/Data/ColumnSort.cs
- src/ProgressOnderwijsUtils/Data/OrderByColumns.cs
- src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs
- src/ProgressOnderwijsUtils/Data/PocoDataReader.cs
- src/ProgressOnderwijsUtils/Data/SqlBatch.cs
- src/ProgressOnderwijsUtils/Pocos/PocoProperties.cs
- src/ProgressOnderwijsUtils/Pocos/PocoProperty.cs
- src/ProgressOnderwijsUtils/Pocos/PocoUtils.cs
In particular, lift restriction on IPocoProperties that it can only return information for IPoco subtypes.
Also make the INestableSql implementations a little easier to copy-paste, since that's what I'm about to do...
> Various code cleanups designed to hopefully make tuple-returning SqlDataReader unpackers easier to implement.

- src/ProgressOnderwijsUtils.AspNetCore/ProgressOnderwijsUtils.AspNetCore.csproj
- src/ProgressOnderwijsUtils.AspNetCore/SecurityHeadersMiddleware.cs
- src/ProgressOnderwijsUtils.AspNetCore/SecurityHeadersMiddlewareOptions.cs
Use as-strict-as-possible settings by default
See also:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy
That way, we don't need to be quite as careful on a case-by-case basis.
> Add COOP and COEP headers

- test/ProgressOnderwijsUtils.Tests/EnumerableExtensionsTests.cs
(changed in some R# version; I didn't bother to check which one)
> Fix warning suppression

- src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtils.Tests/Data/PocoPropertyConvertibleLoaderTest.cs
- test/ProgressOnderwijsUtils.Tests/EnumerableExtensionsTests.cs
Regression in #672 
We probably not actually _need_ this behavior, but it's how it used to work, and changing consumers is more hassle than retaining the behavior.
> fix internal setters

- src/ProgressOnderwijsUtils/BenchTimer.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtils.Tests/BenchmarkTimerTests.cs
- test/ProgressOnderwijsUtils.Tests/Data/ConcatenateSqlTest.cs
- test/ProgressOnderwijsUtils.Tests/EnumerableOfStringExtensionTest.cs
It therefore requires a minimum of 5 runs.
I think this will result in more similar measurements across runs. Or are there better ways to do so?
> Benchtimer now excludes the two most deviating measurements.

- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtils.Tests/NonNullableFieldVerifier1.cs
- test/ProgressOnderwijsUtils.Tests/NonNullableFieldVerifier4.cs
- test/ProgressOnderwijsUtils.Tests/NonNullableNullabilityCheck.cs
- tools/ProgressOnderwijsUtilsBenchmarks/NullabilityBenchmark.cs
#773 
add versie 4 gebaseerd op hardcoded3
versie 1 doet geen string split meer wanneer het gaat om een valide object.
> Maartje/add non nullable field new verifier version + slight optimization version 1

- src/ProgressOnderwijsUtils.AspNetCore/ProgressOnderwijsUtils.AspNetCore.csproj
- src/ProgressOnderwijsUtils.AspNetCore/SecurityHeadersMiddleware.cs
- src/ProgressOnderwijsUtils.AspNetCore/SecurityHeadersMiddlewareOptions.cs
caniuse claims it doesn't work anyhow, and at least on FF I can verify that.
Sticking to the chrome-only but hopefully more future-proof Permissions-Policy therefore.
> Remove feature policy header

- src/ProgressOnderwijsUtils/RequiredFields/NonNullableFieldVerifier4.cs
so that the delegate is always constructed only once, not each call
diff clearer without whitespace changes: https://github.com/progressonderwijs/ProgressOnderwijsUtils/pull/838/files?w=1
> Construct the delegate in a nested static generic class

- src/ProgressOnderwijsUtils/ApprovalTest.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtils.Tests/ApprovalTestTest.cs
For example, I've got an approval that locally succeeds, but fails on the CI. With this extra diff logging, I can analyse the failure on the CI itself.
> For analysis purposes, also provide the first diff when an approval is changed.

- src/ProgressOnderwijsUtils/Extensions/StringUtils.cs
- tools/ProgressOnderwijsUtilsBenchmarks/BenchmarkProgram.cs
- tools/ProgressOnderwijsUtilsBenchmarks/HtmlFragmentBenchmark.cs
Baseline results:
<div>
<pre><code>BenchmarkDotNet=v0.13.5, OS=Windows 11 (10.0.22621.1848/22H2/2022Update/SunValley2)
AMD Ryzen 9 7950X, 1 CPU, 32 logical and 16 physical cores
.NET SDK=7.0.400-preview.23274.1
[Host] : .NET 7.0.7 (7.0.723.27404), X64 RyuJIT AVX2
</code></pre>
<pre><code>Job=Server  Force=False  Server=True  
Toolchain=InProcessEmitToolchain  InvocationCount=256  IterationCount=100  
LaunchCount=1  UnrollFactor=16  WarmupCount=1  
</code></pre>
<table>
<thead><tr><th> Method</th><th>Mean</th><th>Error</th><th>StdDev</th><th>Gen0</th><th>Gen1</th><th>Gen2</th><th>Allocated</th>
</tr>
</thead><tbody><tr><td>WriteToString</td><td>446.1 μs</td><td>2.61 μs</td><td>6.97 μs</td><td>109.3750</td><td>109.3750</td><td>109.3750</td><td>452.63 KB</td> …
> Baseline for html->pipe (memory) benchmark

- src/ProgressOnderwijsUtils/SchemaReflection/DatabaseDefinitionScripter.cs
- test/ProgressOnderwijsUtils.Tests/Data/AsSqlInExpressionTest.cs
- test/ProgressOnderwijsUtils.Tests/Data/ConcatenateSqlTest.cs
- test/ProgressOnderwijsUtils.Tests/Data/DatabaseDescriptionTest.cs
- test/ProgressOnderwijsUtils.Tests/Data/ParameterValuesForDebuggingExtensionTest.cs
- test/ProgressOnderwijsUtils.Tests/Data/ParameterizedSqlTest.cs
- test/ProgressOnderwijsUtils.Tests/Data/TableValuedParameterTest.cs
- test/ProgressOnderwijsUtils.Tests/Data/TestSqlParameterComponent.cs
- test/ProgressOnderwijsUtils.Tests/PocoUtilsTest.cs
- https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/interpolated-string-handler
- https://github.com/progressonderwijs/progress/issues/43386
- Motivation: string interpolations using `InterpolatedStringHandler` aren't supported in expression trees.
- i.e. just don't use those in PAssert tests, which is something specifically common in tests of SQL($...) syntax, of course.
- should purely be a refactor; this just updates the tests so they _can_ compile using InterpolatedStringHandler, it doesn't actually use one.
> Prep potential use of InterpolatedStringHandler

- src/ProgressOnderwijsUtils/Data/ColumnDefinition.cs
- src/ProgressOnderwijsUtils/Data/FieldMapping.cs
- src/ProgressOnderwijsUtils/Pocos/BulkInsertTarget.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtils.Tests/Data/BulkInsertTest.cs
- test/ProgressOnderwijsUtils.Tests/Data/PocoBulkCopyFieldMappingTest.cs
- test/ProgressOnderwijsUtils.Tests/Data/PocoBulkCopyTest.cs
- test/ProgressOnderwijsUtils.Tests/Data/PocoObjectMapperTest.cs
Do not exclude computed columns anymore from the to inserted columns
By default, give an error when writing to such computed columns. It can be configured to suppress this sanlity error check though. For example needed for writing a rowversion property to a static byte[8] column.
> Give explicit error when bulk inserting computed columns; error can be suppressed though

- src/ProgressOnderwijsUtils/Html/HtmlFragmentSanitizeExtension.cs
- src/ProgressOnderwijsUtils/Html/HtmlHelpers.cs
- src/ProgressOnderwijsUtils/Html/HtmlSpec.AttributeConstructionMethods.Generated.cs
- src/ProgressOnderwijsUtils/Html/HtmlSpec.AttributeNameInterfaces.Generated.cs
- src/ProgressOnderwijsUtils/Html/HtmlSpec.HtmlTagKinds.Generated.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtils.Tests/HtmlDslGenerator.cs
Zodat als je in github release-notes edit, en je laat een voorlop "+" achter, het nog blijft compileren.
> Allow unary plus

- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- src/ProgressOnderwijsUtils/Win32/Bitlocker.cs
- src/ProgressOnderwijsUtils/Win32/VirusScan.cs
- src/ProgressOnderwijsUtils/Win32/Win32Extentions.cs
- test/ProgressOnderwijsUtils.Tests/Win32/VirusScanTest.cs
Package includes various breaking changes, but dependent code is simple enough that this isn't all that tricky.
- Replaces https://github.com/progressonderwijs/ProgressOnderwijsUtils/pull/1030
> Bump CsWin32 (breaking changes)

- src/ProgressOnderwijsUtils/Data/CascadedDelete.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- test/ProgressOnderwijsUtils.Tests/Data/CascadedDeleteTest.cs
- https://github.com/progressonderwijs/progress/issues/61738
Furthermore replacing the `StopCascading` parameter with this more advanced parameter.
By example:
If the foreign key has a delete specification `on delete set null` then do not delete, but let the FK specification set the value to null, you can use the predicate to accomodate this in the CascadeDelete.
> CascadeDelete: Extra parameter to accommodate foreign key specifications like `on delete set null`

- ProgressOnderwijsUtils.sln.DotSettings
- src/ProgressOnderwijsUtils/Collections/SequenceEqualityComparer.cs
- src/ProgressOnderwijsUtils/Data/ColumnDefinition.cs
- src/ProgressOnderwijsUtils/Data/ParameterizedSql.cs
- src/ProgressOnderwijsUtils/Data/ParameterizedSqlObjectMapper.cs
- src/ProgressOnderwijsUtils/Data/QueryTableValuedParameterComponent.cs
- src/ProgressOnderwijsUtils/Data/SqlParameterComponent.cs
- src/ProgressOnderwijsUtils/Data/TableValuedParameterWrapper.cs
- src/ProgressOnderwijsUtils/Html/HtmlDirectory.cs
- src/ProgressOnderwijsUtils/Html/HtmlToStringExtensions.cs
- src/ProgressOnderwijsUtils/Pocos/SmallBatchInsertImplementation.cs
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtils.csproj
- src/ProgressOnderwijsUtils/ProgressOnderwijsUtilsAssembly.cs
- test/ProgressOnderwijsUtils.Tests/.editorconfig
- test/ProgressOnderwijsUtils.Tests/Data/ParameterizedSqlTest.cs
- test/ProgressOnderwijsUtils.Tests/Data/TableValuedParameterTest.cs
- test/ProgressOnderwijsUtils.Tests/ReferenceEqualityComparerTest.cs
- test/ProgressOnderwijsUtils.Tests/TreeTest.cs
- test/ProgressOnderwijsUtils.Tests/UtilsTest.cs
- tools/ProgressOnderwijsUtilsBenchmarks/BenchmarkProgram.cs
- tools/ProgressOnderwijsUtilsBenchmarks/HtmlFragmentBenchmark.cs
- tools/ProgressOnderwijsUtilsBenchmarks/RandomHelperBenchmark.cs
- also, when applying R# suggestions about collection expressions it became apparent that those aren't supported StructuralEqualityComparer, hence the introduction of `TvpEqualityToken`
- Actual initial motivation: mark ParameterizedSql as readonly, so that a noisy warning in progress is silenced (https://github.com/progressonderwijs/progress/pull/64060#discussion_r1820201783)
- https://github.com/progressonderwijs/progress/issues/63558
> Various code-cleanups and unit tests for untested code

- tools/ProgressOnderwijsUtilsBenchmarks/BenchmarkProgram.cs
- tools/ProgressOnderwijsUtilsBenchmarks/MicroOrmBench/BenchmarkUtil.cs
- tools/ProgressOnderwijsUtilsBenchmarks/MicroOrmBench/DapperBench.cs
- tools/ProgressOnderwijsUtilsBenchmarks/MicroOrmBench/EntityFrameworkBench.cs
- tools/ProgressOnderwijsUtilsBenchmarks/MicroOrmBench/ExampleObject.cs
- tools/ProgressOnderwijsUtilsBenchmarks/MicroOrmBench/HandrolledAdoNetExecutor.cs
- tools/ProgressOnderwijsUtilsBenchmarks/MicroOrmBench/ParameterizedSqlExecutor.cs
- tools/ProgressOnderwijsUtilsBenchmarks/MicroOrmBench/Program.cs
- tools/ProgressOnderwijsUtilsBenchmarks/ProgressOnderwijsUtilsBenchmarks.csproj
The custom implementation still appears to be much faster, even on .net 9 and latest versions of the various libs
On my machine now:
```
Testing 100 groups of 2000 queries with 0-2957 rows
Row-count median: 7; mean: 200.2; 0 rows: 10.95%; 1 row: 19.55%; <50 rows: 69.95% <50
Reporting time per query execution; parallel executions use 16 threads
Warming up...
Benchmarking...
Running 6-column queries
39.8µs ~ 0.24µs parallel;628µs ~ 852.5µs latency; 10.76/3.02/0.01 milliGC;  EF FromSqlInterpolated (fresh contexts)  checksum:40030700
23.9µs ~ 0.28µs parallel;370µs ~ 935.8µs latency; 5.18/2.30/0.24 milliGC;  EF FromSqlInterpolated (reused context)  checksum:40030700
16.4µs ~ 0.09µs parallel;255µs ~ 647.9µs latency; 3.04/2.23/0.00 milliGC;  Dapper  checksum:40030700
18.2µs ~ 0.11µs …
```
> Dust off the micro ORM bench
